service: minimal-lambda
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1
  memorySize: 128
  timeout: 10
  tracing:
    lambda: true
  environment:
    BASIC_AUTH_USERNAME: ${env:BASIC_AUTH_USERNAME}
    BASIC_AUTH_PASSWORD: ${env:BASIC_AUTH_PASSWORD}

functions:
  index:
    handler: dist/index.handler
    url: true
